spring.application.name=storage-backend

storage.base-path=../../storage/
storage.chunk-size=8192
spring.datasource.url=jdbc:mysql://localhost:3306/dfs_db
spring.datasource.username=root
spring.datasource.password=Root@2319932
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true